In [3]:
import numpy as np

# Numpy Operations

## Arithmetic operations

All arithmetic operations on arrays are **element-wise** (point-to-point).

Note, that beside [Arithmetic functions](https://numpy.org/doc/stable/reference/routines.math.html#arithmetic-operations), numpy sumply a great variaty of [Mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html)

Lets have next 2 arrays:

In [38]:
arr1 = np.arange(1, 6)
arr2 = np.ones(5,  dtype=np.int8)

print(arr1)
print(arr2)

[1 2 3 4 5]
[1 1 1 1 1]


### Addition

We can use the '+' operator as a shortcut to np.add()

In [8]:
# add array with scalar:
arr1 + 1 

array([2, 3, 4, 5, 6])

In [15]:
# add two arrays
print(f'arr1: {arr1}')
print(f'arr2: {arr2}')
arr1 + arr2

arr1: [1 2 3 4 5]
arr2: [1 1 1 1 1]


array([2, 3, 4, 5, 6])

### Subtraction

We can use the '-' operator as a shortcut to np.subtract()

In [16]:
# subtract scalar from array:
print(f'arr1: {arr1}')
arr1-1

arr1: [1 2 3 4 5]


array([0, 1, 2, 3, 4])

In [7]:
# subtract two arrays
print(f'arr1: {arr1}')
print(f'arr2: {arr2}')
arr1 - arr2

arr1: [0 1 2 3 4]
arr2: [2 2 2 2 2]


array([-2, -1,  0,  1,  2])

### Multiplication

We can use the '*' operator as a shortcut to np.multiply()

In [18]:
# multiply array with constant:
print(f'arr1: {arr1}')
arr1*5

arr1: [1 2 3 4 5]


array([ 5, 10, 15, 20, 25])

In [19]:
# multiply two arrays
print(f'arr1: {arr1}')
print(f'arr2: {arr2}')
arr1 * arr2

arr1: [1 2 3 4 5]
arr2: [1 1 1 1 1]


array([1, 2, 3, 4, 5])

### Division

We can use the '/' operator as a shortcut to np.divide()

In [10]:
# divide array with constant:
print(f'arr1: {arr1}')
arr1/3

arr1: [0 1 2 3 4]


array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [11]:
# divide two arrays
print(f'arr1: {arr1}')
print(f'arr2: {arr2}')
arr1 / arr2

arr1: [0 1 2 3 4]
arr2: [2 2 2 2 2]


array([0. , 0.5, 1. , 1.5, 2. ])

## Comparison and Logic Operations

### Arrays Comparison

Comparison Operations on ndarrays are **element-wise** (point-to-point).

They return an array of same shape with Boolean values.

Reference: [Comparison functions](https://numpy.org/doc/stable/reference/routines.logic.html#comparison)

In [20]:
### Equal (==) or np.equal() with constant
print(arr1)
print(arr1 == 1)
# print(np.equal(arr1,1))

[1 2 3 4 5]
[ True False False False False]


In [22]:
### Equal (==) or np.equal() with another array
print(arr1)
print(arr2)
print(arr1 == arr2)     
# print(np.equal(arr1,arr2))

[1 2 3 4 5]
[1 1 1 1 1]
[ True False False False False]


In [14]:
### Not equal (!=) or np.not_equal() with constant
print(arr1)
print(arr1 != 1)
# print(np.not_equal(arr1,1))

[0 1 2 3 4]
[ True False  True  True  True]


In [23]:
### Not equal (!=) or np.not_equal() with another array
print(arr1)
print(arr2)
print(arr1 != arr2)
# print(np.not_equal(arr1,arr2))

[1 2 3 4 5]
[1 1 1 1 1]
[False  True  True  True  True]


In [25]:
### Greater (>) or np.greater() with constant
print(arr1)
print(arr1 > 1)
print(np.greater(arr1,1))

[1 2 3 4 5]
[False  True  True  True  True]
[False  True  True  True  True]


In [17]:
### Greater or equal (>=) or np.greater_equal() with another array
print(arr1)
print(arr2)
print(arr1 >= arr2)
# print(np.greater_equal(arr1,arr2))

[0 1 2 3 4]
[2 2 2 2 2]
[False False  True  True  True]


In [18]:
### Less (<) or np.less() with constant
print(arr1)
print(arr1 < 1)
# print(np.less(arr1,1))

[0 1 2 3 4]
[ True False False False False]


In [19]:
### Less or equal (<=) or np.less_equal() with another array
print(arr1)
print(arr2)
print(arr1 <= arr2)
# print(np.less_equal(arr1,arr2))

[0 1 2 3 4]
[2 2 2 2 2]
[ True  True  True False False]


### Logical operations

Logical operations on ndarrays are **element-wise** (point-to-point).

They return an array of same shape with Boolean values.

Logical operations are [commutative](https://en.wikipedia.org/wiki/Commutative_property)

Reference: [Logical operations](https://numpy.org/doc/stable/reference/routines.logic.html#logical-operations)

#### Logical AND

[np.logical_and()](https://numpy.org/doc/stable/reference/generated/numpy.logical_and.html#numpy-logical-and) - Compute the truth value of x1 AND x2 element-wise.

The & operator can be used as a shorthand for np.logical_and() **only on boolean values/ndarrays**.

In [26]:
# logical and between 2 booleans:
True & False            
# np.logical_and(True, False)

False

In [27]:
# logical and between 2 boolean arrays:
print(f'arr1: {arr1}')
print(f'arr2: {arr2}','\n')

x = arr1>2
y = arr2>1
print(f'x: {x}')
print(f'y: {y}','\n')

print(f'x&y: {x&y}')
# print(np.logical_and(x,y))


arr1: [1 2 3 4 5]
arr2: [1 1 1 1 1] 

x: [False False  True  True  True]
y: [False False False False False] 

x&y: [False False False False False]


In [22]:
# logical and between 2 scalars:
# note that a value=0 is interpreted as False,
# and a value != 0 is interpreted as True

print(np.logical_and(1, -92349))
print(np.logical_and(1, 0))

True
False


#### Logical OR

<img src="../images/logical_or.png">

[np.logical_or()](https://numpy.org/doc/stable/reference/generated/numpy.logical_or.html#numpy-logical-or) - Compute the truth value of x1 OR x2 element-wise.

The | operator can be used as a shorthand for np.logical_or() **only on boolean values/ndarrays**.

In [23]:
# logical or between 2 booleans:
True | False
# np.logical_or(True, False)

True

In [29]:
# logical or between 2 boolean arrays:
print(f'arr1: {arr1}')
print(f'arr2: {arr2}','\n')

x = arr1>2
y = arr2>1
print(f'x: {x}')
print(f'y: {y}','\n')

print(f'x|y: {x|y}')
# print(np.logical_or(x,y))


arr1: [1 2 3 4 5]
arr2: [1 1 1 1 1] 

x: [False False  True  True  True]
y: [False False False False False] 

x|y: [False False  True  True  True]


In [30]:
# logical or between 2 scalars:
print(np.logical_or(1, -92349))
print(np.logical_or(1, 0))
print(np.logical_or(0, 0))

True
True
False


#### Logical NOT

[np.logical_not()](https://numpy.org/doc/stable/reference/generated/numpy.logical_not.html#numpy-logical-not) - Compute the truth value of NOT x element-wise.

In [31]:
# logical not on scalar:
print(np.logical_not(True))
print(np.logical_not(0))
print(np.logical_not(-92349))

False
True
False


In [32]:
# logical not on boolean array:
print(f'arr1: {arr1}')
arr2 = arr1>2
print(f'arr2: {arr2}')
print(np.logical_not(arr2))

arr1: [1 2 3 4 5]
arr2: [False False  True  True  True]
[ True  True False False False]


### Truth value testing

[np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html#numpy.all) - Test whether all array elements along a given axis evaluate to True.

[np.any()](https://numpy.org/doc/stable/reference/generated/numpy.any.html#numpy.any) - Test whether any array element along a given axis evaluates to True.

In [33]:
arr2 = np.array([True, False, True])
print("Any true in arr2:", np.any(arr2))
print("All true in arr2:", np.all(arr2))

Any true in arr2: True
All true in arr2: False


In [40]:
print(arr1)
print(arr2)

[1 2 3 4 5]
[1 1 1 1 1]


In [46]:
np.any(arr1 > 10, 0)

np.False_