In [3]:
import numpy as np

In [ ]:
# ---------------------------------- Task 1 ---------------------------------- #
""" DESCRIPTION:
Create a function (create_numpy_array) that takes a list of numbers and returns a NumPy array.
"""

## YOUR CODE HERE:

In [1]:
def create_numpy_array(num):
    return np.array(num)

In [4]:
### TEST:
print(create_numpy_array([1, 2, 3, 4, 5]))

[1 2 3 4 5]


## EXPECTED OUTPUT:
[1 2 3 4 5]

In [ ]:
# ---------------------------------- Task 2 ---------------------------------- #
"""
DESCRIPTION:
Create a function (array_sum) that takes a NumPy array and returns the sum of its elements.
"""

In [5]:
## YOUR CODE HERE:

def array_sum(arr):
    return arr.sum()

In [6]:
### TEST:
print(array_sum(np.array([1, 2, 3, 4, 5])))


15


## EXPECTED OUTPUT:
15

In [ ]:
# ---------------------------------- Task 3 ---------------------------------- #
""" DESCRIPTION:
Create a function (evens_in_array) that takes a NumPy array and returns a new array containing only the even numbers.
"""

In [7]:
## YOUR CODE HERE:

def evens_in_array(arr):
    mask=arr%2==0
    return arr[mask]

In [8]:
### TEST:
print(evens_in_array(np.array([1, 2, 3, 4, 5, 6])))

[2 4 6]


## EXPECTED OUTPUT:
[2 4 6]

In [ ]:
# ---------------------------------- Task 4 ---------------------------------- #
""" DESCRIPTION:
Create a function (count_greater_than) that takes a NumPy array and a threshold value, and returns the count of elements greater than the threshold.
"""

In [13]:
## YOUR CODE HERE:

def count_greater_than(arr, threshold_val):
    mask= arr > threshold_val 
    return len(arr[mask])


In [14]:
### TEST:
print(count_greater_than(np.array([1, 2, 3, 4, 5]), 3))

2


## EXPECTED OUTPUT:
2

In [ ]:
# ---------------------------------- Task 5 ---------------------------------- #
""" DESCRIPTION:
Create a function (access_element) that takes a NumPy array and an index, and returns the element at that index.
"""

In [15]:
## YOUR CODE HERE:

def access_element(arr, idx):
    return arr[idx]

In [16]:
### TEST:
print(access_element(np.array([10, 20, 30, 40, 50]), 3))

40


## EXPECTED OUTPUT:
40

In [ ]:
# ---------------------------------- Task 6 ---------------------------------- #
""" DESCRIPTION:
Create a function (slice_array) that takes a NumPy array and two indices, start and end, and returns the sliced array.
"""

In [25]:
## YOUR CODE HERE:

def slice_array(arr, idx_tuple):
    start_idx, end_idx = idx_tuple
    return arr[start_idx:end_idx]
    

In [28]:
### TEST:
print(slice_array(np.array([10, 20, 30, 40, 50]), (1, 4)))

[20 30 40]


## EXPECTED OUTPUT:
[20 30 40]