In [1]:
import numpy as np

## Indexing and slicing

### One-dimensional Array Indexing and Slicing


**Indexing Syntax**: array[n]

n >= 0 => get n+1 element, from left to right

n <= -1 => get n element, from right to left 


**Slicing Syntax**: array[start:stop:step]

start = index of start element. Default = beginning of array.

stop -1 = index of last element. Default = end of array (inclusive)

step   = the step to increment indexes on slice. Optional. Default 1.

<img src="./images/1Darray-slice.png" alt="1d_2d_3d_arrays.png" style="height: 300px;">

In [2]:
a1 = np.arange(1,10)
print(f'a1: {a1}')

print("\npositive index - from left to right")
print(f'a[1]: {a1[1]}')

print("\nnegative index - from right to left")
print(f'a[-1]: {a1[-1]}')

print("\nget elements with indexes 0 up to 3 (excluded)")
print(f'a[0:3]: {a1[0:3]}')

print("\nget all elements")
print(f'a[::]: {a1[::]}')

print("\nget all elements, without the last one")
print(f'a[:-1]: {a1[:-1]}')

print("\nslicing with step")
print(f'a[::2]: {a1[::2]}')

print("\nslicing with step - backwards")
print(f'a[::-2]: {a1[::-2]}')

print("\nreverse array")
print(f'a[::-1]: {a1[::-1]}')

a1: [1 2 3 4 5 6 7 8 9]

positive index - from left to right
a[1]: 2

negative index - from right to left
a[-1]: 9

get elements with indexes 0 up to 3 (excluded)
a[0:3]: [1 2 3]

get all elements
a[::]: [1 2 3 4 5 6 7 8 9]

get all elements, without the last one
a[:-1]: [1 2 3 4 5 6 7 8]

slicing with step
a[::2]: [1 3 5 7 9]

slicing with step - backwards
a[::-2]: [9 7 5 3 1]

reverse array
a[::-1]: [9 8 7 6 5 4 3 2 1]


### Multi dimensional arrays indexing and slicing


**Indexing Syntax**: matrix[i,j]

i - index rows

j - index columns



**Slicing Syntax:**: matrix[start:stop:step, start:stop:step]

In [43]:
# let's have next 2D array:
arr = np.arange(12).reshape(3, 4)

print(f'arr:\n{arr}')


# print("\nSlice the first row")
# print(arr[0,:])

print("\nSlice the first column")
print(arr[:,1])

print("\nSlice first 2 rows and 2 columns")
print(arr[0:2, 1]) 

print(arr.shape[1])

print("\nSlice the corner elements")
print(arr[::arr.shape[0]-1, ::arr.shape[1]-1])
 

arr:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Slice the first column
[1 5 9]

Slice first 2 rows and 2 columns
[1 5]
4

Slice the corner elements
[[ 0  3]
 [ 8 11]]


## Advanced Indexing 

Numpy's advanced indexing allows you to access elements of an array using non-standard indexing techniques, offering greater flexibility than basic slicing. 
There are two types of advanced indexing: integer and boolean.



### Boolean indexing

We can select certain values from a numpy array, if we mask (filter) it with a Boolean array (True/False values) with the **same shape** as the original array.

In [4]:
# let's have next array:
a = np.arange(1,6)
print(f'a: {a}')

# this is the filter mask:
mask = [True, True, False, True, False]

# apply the filter as index, and get only the elements for which the mask is True:
print(f'masked: {a[mask]}')

a: [1 2 3 4 5]
masked: [1 2 4]


#### Masking example 1 : select only the even values

In [46]:
# let's have next array:
a = np.arange(1,20)
print(f'a: {a}')

# and get only even numbers from it:
mask = a%2==0
print(mask)
a[mask]

a: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

How it works:

a%2 is calculated for each element of the array.

If result value, which serves as index, is True => the element is selected, 
if it is False the element is not selected 

#### Masking example 2 : group 'scores' by category

Let's have an array of 'scores', and for each score we'll have to assign a category from a predefined list.
The goal is to group scores (first column) under 'bad' and 'good' categories, based on the second column.

In [50]:
# Define the scores array
scores = np.array([
    [4, 1],
    [2, 0],
    [3, 0],
    [5, 1],
    [6, 1]
])

# Define the categories
categories = ['bad', 'good']
print(scores[:, 1] == 1)
# Extract the indices for each category
bad_mask = scores[:, 1] == 0
good_mask = scores[:, 1] == 1

# Group scores by 'good' category
good_scores = scores[good_mask, 0]

# Group scores by 'bad' category
bad_scores = scores[bad_mask, 0]

# Print the results
# print(f"Scores in 'good' category: {good_scores}")
# print(f"Scores in 'bad' category: {bad_scores}")

[ True False False  True  True]


### Integer Array Indexing:

Integer array indexing allows selection of arbitrary items in the array.

#### Example: use a list of integers as indices to select elements from an array

In [52]:
a = np.array([10, 20, 30, 40])
print(a[[0,2]])



[10 30]


#### Example: map list elements to array of indexes

NumPy provides an efficient way to map elements from a list to an array of indexes using advanced indexing.


Advanced array indexing is useful for mapping elements in one array with values from another list or array based on specific indexes.


*Example Scenario*:
    
Given a NumPy array of repeated indexes (e.g., <code>[0, 2, 1, 2, 0, 1, 2]</code>) and a corresponding list of colors (e.g., <code>['red', 'green', 'blue']</code>), map each index in the array to its respective color.
			

In [53]:
# let's have a numpy array of repeated values 0, 1 or 2:
indexes = np.array([0, 2, 1, 2, 0, 1, 2])

# and an array of colors:
colors = np.array(['red', 'green', 'blue'])

# Mapping indexes to colors using advanced indexing
mapped_colors = colors[indexes]

print("Mapped colors:", mapped_colors)

Mapped colors: ['red' 'blue' 'green' 'blue' 'red' 'green' 'blue']


In [54]:
# Define the array of elements
elements = np.array([100, 200, 300, 400, 500])

# Define the indices of elements to select
indices = np.array([0, 2, 4])

# Use advanced indexing to select elements
selected_elements = elements[indices]

# Print the selected elements
print("Selected elements:", selected_elements)

Selected elements: [100 300 500]


In [65]:
arr = np.array(['Mercedes', 'BMW', 'Audi', 'Tesla', 'BMW', 'BMW', 'Audi', 'Audi'])
indices = np.array([2, 0, 0, 0, 0, 0])

arr[indices]

array(['Audi', 'Mercedes', 'Mercedes', 'Mercedes', 'Mercedes', 'Mercedes'],
      dtype='<U8')